/*
=======================================================================================================================
Magnitude Analysis
=======================================================================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
=======================================================================================================================
*/

-- Find total customers by countries
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

-- Find total customers by gender
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;

-- Find total products by category
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC;

-- What is the average costs in each category?
SELECT 
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

-- What is the total revenue generated for each category?
SELECT 
    d.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products d
    ON f.product_key = d.product_key
GROUP BY d.category
ORDER BY SUM(f.sales_amount) DESC;

-- What is the total revenue generated by each customer?
SELECT 
    d.customer_key,
    d.first_name,
    d.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers d
    ON f.customer_key = d.customer_key
GROUP BY d.customer_key,
         d.first_name,
         d.last_name
ORDER BY SUM(f.sales_amount) DESC;

-- What is the distribution of sold items across countries?
SELECT 
    d.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers d
    ON f.customer_key = d.customer_key
GROUP BY d.country
ORDER BY SUM(f.quantity) DESC;